### ISSUE TITLE
Thank You!!

### ISSUE THREAD

**Issue by NicoM1** [wiggin77/HxMongoNode#1]
This is the first wrapper I've found that actually works on haxe 3.2, thank you so much! I was using untyped code before and it was scary:O I did have to just hack a couple things into your externs like MongoCursor.sort, and MongoCollection.save, but it seems to be working so far (also had to change some things that worked untyped but don't now, like using collections directly without an async handler)

sorry for the possibly confusing ramble, but thank you,
Nico

**Comment by wiggin77** [comment]
Glad it's useful to you.  I'm still working on it, as it's only about halfway finished getting the types completed, but the untyped stuff should still work in the meantime.  Also, if you have anything that can be merged please send a pull request. Thx.

**Comment by NicoM1** [comment]
Cool, again I really appreciate this, its being used on the backend of http://slickrock.io (in soft launch but you can check it out if you want),

Nico

From: wiggin77
Sent: ‎Saturday‎, ‎June‎ ‎27‎, ‎2015 ‎9‎:‎07‎ ‎PM
To: wiggin77/hxmongodb
Cc: Nico May

Glad it's useful to you. I'm still working on it, as it's only about halfway finished getting the types completed, but the untyped stuff should still work in the meantime.
